// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "focus-tabs": {
      name: "focus-tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/focus-tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/focus-tabs.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button": {
      name: "icon-hover-button",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/annui/icon-hover-button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/icon-hover-button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "adaptive-container": {
      name: "adaptive-container",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/adaptive-container.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/adaptive-container.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-00": {
      name: "dropdown-menu-00",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/dropdown-menu-00.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/dropdown-menu-00.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "vercel-tabs": {
      name: "vercel-tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/vercel-tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/vercel-tabs.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select-filter": {
      name: "select-filter",
      description: "",
      type: "registry:ui",
      registryDependencies: ["colored-label"],
      files: [{
        path: "registry/default/annui/select-filter.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/select-filter.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-00": {
      name: "tabs-00",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/tabs-00.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/tabs-00.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-01": {
      name: "tabs-01",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/tabs-01.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/tabs-01.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "image-carousel": {
      name: "image-carousel",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/image-carousel.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/image-carousel.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "detail-panel": {
      name: "detail-panel",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/detail-panel.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/detail-panel.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "colored-label": {
      name: "colored-label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/annui/colored-label.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/annui/colored-label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "focus-tabs-demo": {
      name: "focus-tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["focus-tabs"],
      files: [{
        path: "registry/default/example/focus-tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/focus-tabs-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "focus-tabs-variant": {
      name: "focus-tabs-variant",
      description: "",
      type: "registry:example",
      registryDependencies: ["focus-tabs"],
      files: [{
        path: "registry/default/example/focus-tabs-variant.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/focus-tabs-variant.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button-demo": {
      name: "icon-hover-button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-hover-button"],
      files: [{
        path: "registry/default/example/icon-hover-button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/icon-hover-button-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button-primary": {
      name: "icon-hover-button-primary",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-hover-button"],
      files: [{
        path: "registry/default/example/icon-hover-button-primary.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/icon-hover-button-primary.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button-secondary": {
      name: "icon-hover-button-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-hover-button"],
      files: [{
        path: "registry/default/example/icon-hover-button-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/icon-hover-button-secondary.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button-destructive": {
      name: "icon-hover-button-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-hover-button"],
      files: [{
        path: "registry/default/example/icon-hover-button-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/icon-hover-button-destructive.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button-outline": {
      name: "icon-hover-button-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-hover-button"],
      files: [{
        path: "registry/default/example/icon-hover-button-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/icon-hover-button-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button-ghost": {
      name: "icon-hover-button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-hover-button"],
      files: [{
        path: "registry/default/example/icon-hover-button-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/icon-hover-button-ghost.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button-link": {
      name: "icon-hover-button-link",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-hover-button"],
      files: [{
        path: "registry/default/example/icon-hover-button-link.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/icon-hover-button-link.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "icon-hover-button-both-side": {
      name: "icon-hover-button-both-side",
      description: "",
      type: "registry:example",
      registryDependencies: ["icon-hover-button"],
      files: [{
        path: "registry/default/example/icon-hover-button-both-side.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/icon-hover-button-both-side.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "adaptive-container-demo": {
      name: "adaptive-container-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["adaptive-container","button"],
      files: [{
        path: "registry/default/example/adaptive-container-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/adaptive-container-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-00-demo": {
      name: "dropdown-menu-00-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu-00","button"],
      files: [{
        path: "registry/default/example/dropdown-menu-00-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/dropdown-menu-00-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-00-variant": {
      name: "dropdown-menu-00-variant",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu-00","button"],
      files: [{
        path: "registry/default/example/dropdown-menu-00-variant.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/dropdown-menu-00-variant.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "vercel-tabs-demo": {
      name: "vercel-tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["vercel-tabs"],
      files: [{
        path: "registry/default/example/vercel-tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/vercel-tabs-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select-filter-demo": {
      name: "select-filter-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["select-filter"],
      files: [{
        path: "registry/default/example/select-filter-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/select-filter-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-00-demo": {
      name: "tabs-00-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs-00"],
      files: [{
        path: "registry/default/example/tabs-00-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/tabs-00-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-00-underline": {
      name: "tabs-00-underline",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs-00"],
      files: [{
        path: "registry/default/example/tabs-00-underline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/tabs-00-underline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-00-hover-underline": {
      name: "tabs-00-hover-underline",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs-00"],
      files: [{
        path: "registry/default/example/tabs-00-hover-underline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/tabs-00-hover-underline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-01-demo": {
      name: "tabs-01-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs-01"],
      files: [{
        path: "registry/default/example/tabs-01-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/tabs-01-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "image-carousel-demo": {
      name: "image-carousel-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image-carousel"],
      files: [{
        path: "registry/default/example/image-carousel-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/image-carousel-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "image-carousel-collapsible": {
      name: "image-carousel-collapsible",
      description: "",
      type: "registry:example",
      registryDependencies: ["image-carousel"],
      files: [{
        path: "registry/default/example/image-carousel-collapsible.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/image-carousel-collapsible.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "detail-panel-demo": {
      name: "detail-panel-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["detail-panel","colored-label"],
      files: [{
        path: "registry/default/example/detail-panel-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/detail-panel-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "detail-panel-sheet": {
      name: "detail-panel-sheet",
      description: "",
      type: "registry:example",
      registryDependencies: ["detail-panel","sheet"],
      files: [{
        path: "registry/default/example/detail-panel-sheet.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/detail-panel-sheet.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "colored-label-demo": {
      name: "colored-label-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["colored-label"],
      files: [{
        path: "registry/default/example/colored-label-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/colored-label-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "colored-label-colors": {
      name: "colored-label-colors",
      description: "",
      type: "registry:example",
      registryDependencies: ["colored-label"],
      files: [{
        path: "registry/default/example/colored-label-colors.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/colored-label-colors.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "colored-label-opacity": {
      name: "colored-label-opacity",
      description: "",
      type: "registry:example",
      registryDependencies: ["colored-label"],
      files: [{
        path: "registry/default/example/colored-label-opacity.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/colored-label-opacity.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "colored-label-dark": {
      name: "colored-label-dark",
      description: "",
      type: "registry:example",
      registryDependencies: ["colored-label"],
      files: [{
        path: "registry/default/example/colored-label-dark.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/colored-label-dark.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "context": {
      name: "context",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/context.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/context.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
